POST http://localhost:3000/login
Content-Type: application/json

{
    "email" : "aaa@gmail.com",
    "password" : "aaaaaaa"
}

###
GET http://localhost:3000/

Content-Type: application/json

{
    "email" : "aaa@gmail.com",
    "password" : "aaaaaaa"
}